# Generated by Django 5.1.1 on 2024-09-26 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AskChatgpt',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=10)),
                ('question', models.TextField()),
                ('response', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 't_ask_chatgpt',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=10)),
                ('ranking', models.IntegerField()),
                ('observation', models.TextField()),
                ('date', models.DateField()),
            ],
            options={
                'db_table': 't_feedback',
            },
        ),
        migrations.CreateModel(
            name='FrequentQuestions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('active', models.IntegerField()),
            ],
            options={
                'db_table': 't_frequent_questions',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=50, null=True, unique=True)),
                ('identification', models.CharField(max_length=10)),
                ('phone', models.IntegerField(null=True, unique=True)),
                ('ask', models.CharField(max_length=1000, null=True)),
            ],
            options={
                'db_table': 't_comments',
                'unique_together': {('email', 'identification', 'phone')},
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('identification', models.CharField(max_length=10, unique=True)),
                ('otp', models.IntegerField(blank=True, null=True)),
                ('password', models.CharField(max_length=1000)),
                ('insurance_type', models.IntegerField(blank=True, null=True)),
                ('document_type', models.IntegerField()),
                ('date_expiration', models.DateField()),
                ('role', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 't_user',
                'unique_together': {('email', 'identification')},
            },
        ),
    ]
