# Generated by Django 5.1.1 on 2024-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_comments_unique_together_remove_comments_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askchatgpt',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
