# Generated by Django 5.1.1 on 2024-09-27 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_askchatgpt_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askchatgpt',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='askchatgpt',
            name='identification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
