# Generated by Django 5.1.1 on 2024-10-05 03:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_askchatgpt_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequentquestions',
            name='answers',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedback',
            name='identification',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
