# Generated by Django 5.1.1 on 2024-10-05 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_frequentquestions_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequentquestions',
            old_name='answers',
            new_name='answer',
        ),
    ]
