# Generated by Django 5.1.1 on 2024-10-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_answers_frequentquestions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='notification',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
