# Generated by Django 5.1.1 on 2024-10-10 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_user_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('identification', models.CharField(max_length=10)),
                ('seenAt', models.IntegerField(null=True)),
                ('message', models.TextField()),
            ],
        ),
    ]
