# Generated by Django 5.1.1 on 2024-10-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='notification',
        ),
        migrations.AddField(
            model_name='user',
            name='notificationInsurance',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='user',
            name='notificationOthers',
            field=models.IntegerField(default=1),
        ),
    ]
