# Generated by Django 5.1.1 on 2024-10-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_notification_user_notificationinsurance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='notificationInsurance',
            new_name='notification_insurance',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='notificationOthers',
            new_name='notification_others',
        ),
        migrations.AddField(
            model_name='notifications',
            name='notification_type',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
