# Generated by Django 5.1.1 on 2024-10-14 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_rename_notificationinsurance_user_notification_insurance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='contacted',
            field=models.IntegerField(default=0),
        ),
    ]
