# Generated by Django 5.1.1 on 2024-10-26 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_comments_contacted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
