name: Deploy to Railway via Docker

on:
  push:
    branches:
      - main  # o cambia esto por la rama que uses

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/prueba:latest .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/prueba:latest

    - name: Trigger Railway Deploy
      run: |
        curl -X POST https://backboard.railway.app/graphql \
        -H "Content-Type: application/json" \
        -H "Authorization: Bearer ${{ secrets.RAILWAY_TOKEN }}" \
        -d '{"query":"mutation { deployProject(input: { projectId: \"${{ secrets.RAILWAY_PROJECT_ID }}\" }) { id } }"}'
